### ISSUE TITLE
Possible duplicate/interesting read

### ISSUE THREAD

**Issue by dpdani** [Steffo99/async-telegram#1]
http://szastupov.github.io/aiotg/index.html

Forse potresti forkare questa libreria?

**Comment by Steffo99** [comment]
Grazie!

Mi sa che faccio prima a forkare quella libreria e aggiungerci una cronologia dei messaggi che finire di sviluppare e debuggare la mia...

Appena ho un po' di tempo ci guardo meglio.

**Comment by dpdani** [comment]
👍
Magari gli piace pure e ti accettano una pull request
